### ISSUE TITLE
您好，我想请问一下steam令牌算法是什么？

### ISSUE THREAD

**Issue by NatsumiXD** [Koukotsukan/Steam-Backup-Token-Manager#1]
我已经拥有我的secret
但是如何通过secret生成令牌？

**Comment by Koukotsukan** [comment]
嗨！

这是一个本地的令牌管理器，应用本身不涉及算法，需要您自行复制您在steam官网生成的备用令牌进去才能进行管理，目的是为了方便管理备用令牌的使用。

谢谢您提问。

**Comment by NatsumiXD** [comment]
感谢
